### ISSUE TITLE
Error on adding plugin by non-existing repository url

### ISSUE THREAD

**Issue by wuzyk** [rispa-io/rispa-cli#24]
Command `ris add` updates rispa.json and makes a commit even if repository url is not correct and plugin is not installed

**Comment by Fyzu** [comment]
Need to check this, mb problem was solved after #19

**Comment by wuzyk** [comment]
The issue is still there.
![20170627112406 1](https://user-images.githubusercontent.com/1822939/27573631-317ecf06-5b2c-11e7-9537-1ce33f8a8d2e.png)

**Comment by Laiff** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Resolve rispa-cli#24](https://trello.com/c/5mNnvcpk/48-resolve-rispa-cli24)

**Comment by Laiff** [comment]
Resolved via #35
